### ISSUE TITLE
Most of the apiso:ServiceTypes are missing on csw query

### ISSUE THREAD

**Issue by rsignell-usgs** [ioos/catalog#78] opened 2020-05-19 11:10 UTC
I'm not sure whether this is a catalog service or a client issue, but this owslib CSW query:
```python
from owslib.csw import CatalogueServiceWeb
endpoint = 'https://data.ioos.us/csw' 
csw = CatalogueServiceWeb(endpoint,timeout=60)
csw.get_operation_by_name('GetDomain')
csw.getdomain('apiso:ServiceType', 'property')
print(csw.results['values'])
```
that used to return:
```
['THREDDS OPeNDAP,Open Geospatial Consortium Web Map Service (WMS),THREDDS NetCDF Subset Service', 'ERDDAP OPeNDAP', 'Open Geospatial Consortium Web Map Service (WMS),Open Geospatial Consortium Web Feature Service (WFS)', 'Open Geospatial Consortium Web Feature Service (WFS),Open Geospatial Consortium Web Map Service (WMS)', 'THREDDS OPeNDAP,Open Geospatial Consortium Sensor Observation Service (SOS),THREDDS HTTP Service', 'THREDDS OPeNDAP,Open Geospatial Consortium Web Coverage Service (WCS),Open Geospatial Consortium Web Map Service (WMS),THREDDS NetCDF Subset Service', 'THREDDS OPeNDAP,Open Geospatial Consortium Web Coverage Service (WCS),Open Geospatial Consortium Sensor Observation Service (SOS),THREDDS NetCDF Subset Service', 'THREDDS OPeNDAP,Open Geospatial Consortium Web Coverage Service (WCS),THREDDS NetCDF Subset Service', 'ERDDAP tabledap,OPeNDAP,ERDDAP Subset', 'THREDDS OPeNDAP,Open Geospatial Consortium Sensor Observation Service (SOS)', 'OPeNDAP:OPeNDAP,file', 'ERDDAP OPeNDAP,Open Geospatial Consortium Web Map Service (WMS)', None, 'THREDDS OPeNDAP,Open Geospatial Consortium Web Map Service (WMS)', 'ERDDAP tabledap,OPeNDAP', 'OPeNDAP:OPeNDAP', 'THREDDS OPeNDAP,Open Geospatial Consortium Web Map Service (WMS),THREDDS HTTP Service', 'Open Geospatial Consortium Web Coverage Service (WCS),Open Geospatial Consortium Web Map Service (WMS),Open Geospatial Consortium Web Map Service - Cached (WMS-C)', 'OGC:SOS', 'THREDDS OPeNDAP,THREDDS HTTP Service', 'ERDDAP griddap,OPeNDAP,Open Geospatial Consortium Web Map Service (WMS)', 'Open Geospatial Consortium Web Feature Service (WFS),Open Geospatial Consortium Web Map Service (WMS),Open Geospatial Consortium Web Map Service - Cached (WMS-C)', 'THREDDS OPeNDAP', 'Open Geospatial Consortium Web Map Service (WMS)']
```
now returns just:
```
['OGC:SOS', 'OGC:WMS']
```

cc @ocefpaf, @benjwadams

**Comment by mwengren** [comment] 2020-05-19 11:56
I would have guessed this might be due to the CS-W service not replicating all the CKAN records properly, which happens sometimes, but the CS-W record count (20705):

https://data.ioos.us/csw?request=GetRecords&service=CSW&version=3.0.0&typenames=gmd:MD_Metadata&OutputSchema=http://www.isotc211.org/2005/gmd

looks to be ballpark comparable to what's in the Catalog (20723):

https://data.ioos.us/api/3/action/package_search  or
https://data.ioos.us/dataset

Also, the Catalog UI itself shows many different formats available - look at the 'Formats' filter control on the left menu on the last link above.

@benjwadams can probably dig deeper into Catalog details if necessary, but perhaps it's a client library or code problem?

**Comment by rsignell-usgs** [comment] 2020-05-19 15:15
@mwengren I agree something seems broken between CKAN and pycsw, because  as you say, the services types are there on CKAN, just not on the pycsw side anymore.   I think it's beyond just an issue of replication, because the services just seem missing from all datasets on the pycsw side.   

See Cell [11] of [this notebook](https://gist.github.com/rsignell-usgs/413199053d71978586501aa5405bc5c6) for example.    The `scheme` for all the services is `None`.  

![2020-05-19_11-11-19](https://user-images.githubusercontent.com/1872600/82344412-054f2700-99c2-11ea-9fc9-96f6791ed706.png)

**Comment by rsignell-usgs** [comment] 2020-05-19 15:51
So @benjwadams , both of these issues are caused by the [pycsw python 2 comma issue](https://github.com/geopython/pycsw/issues/572)?

**Comment by benjwadams** [comment] 2020-05-20 21:27
I'm not sure yet.  The PyCSW server process runs in its own container.  I'm using an image with a code base has the fix for PyCSW applied, but this problem is occurring again.   I'm looking for the root cause of the issue.

**Comment by benjwadams** [comment] 2020-05-20 21:28
I'm not sure yet.  The PyCSW server process runs in its own container.  I'm using an image with a code base has the fix for PyCSW applied.   I'm looking for the root cause of the issue.

**Comment by rsignell-usgs** [comment] 2020-10-15 12:53
@benjwadams , I just ran this again:
```
from owslib.csw import CatalogueServiceWeb
endpoint = 'https://data.ioos.us/csw' 
csw = CatalogueServiceWeb(endpoint,timeout=60)
csw.get_operation_by_name('GetDomain')
csw.getdomain('apiso:ServiceType', 'property')
print(csw.results['values'])
```
and I get:
```
['OGC:SOS', 'OGC:WMS', 'SOS']
```
So still no OPeNDAP or other services.   

Back in May when I first reported this we got these two:
```
['OGC:SOS', 'OGC:WMS']
```
Does that give any additional clues about the problem?

**Comment by rsignell-usgs** [comment] 2020-10-21 13:32
@benjwadams back on May 20 you said "I'm looking for the root cause of the issue."
Any updates?

**Comment by benjwadams** [comment] 2020-10-30 15:52
@rsignell-usgs , sorry for the delay.  Earlier I seeing if it was a CKAN issue, didn't get very far with that approach as a resolution.

I revisited this again, and upgrading some of the plugins, especially ckanext-spatial, seems to have fixed the issue.  Earlier versions of ckanext-spatial used PyCSW client commands from the 1.x series, but the code was updated to PyCSW 2 code instead.  We were always running PyCSW 2 as the CSW backend, but it appears some of the client commands ckanext-spatial was emitting were from the 1.x branches.

https://data.ioos.us/csw?service=CSW&version=2.0.2&request=GetDomain&propertyname=apiso:ServiceType  is now showing many more unique entries for the `apiso:ServiceType` element.  Please check the output of the CSW and see if the changes made were sufficient to fix the issues with the CSW you were encountering.

**Comment by benjwadams** [comment] 2020-12-07 16:35
Closing issue as CSW results are now populating.

**Closed as completed by benjwadams** 2020-12-07 16:35 UTC
