### ISSUE TITLE
Diagnose CKAN <-> pyscw synchronization issues

### ISSUE THREAD

**Issue by mwengren** [ioos/catalog#53] opened 2017-08-31 15:56 UTC
Per https://github.com/ioos/notebooks_demos/pull/128, it seems that the pycsw database may not be updating reliably from the CKAN database. 

Test case is the [Catalog's 1KM West Coast HFR Dataset](https://data.ioos.us/dataset/near-real-time-surface-ocean-velocity-u-s-west-coast1-km-resolution2) from Scripps, which can only be retrieved by querying with a time range of the past month vs. past week, although the temporal extent in CKAN covers up to the past day or so.   See [Jupyter Notebook](http://nbviewer.jupyter.org/urls/gist.githubusercontent.com/ocefpaf/b45877a314468f6c1e66dcf31eee610d/raw/5191c2c2f661581d8509c58c97a63af87818629e/debug_hfradar.ipynb) showing query results.

cc @ocefpaf

**Comment by mwengren** [comment] 2017-09-14 13:47
@ocefpaf Any chance you could re-run this notebook and post how far back you need to filter the date by in order to get any of the SCRIPPS HFR records back?  

Trying to figure out if pycsw is updating or not since we first looked at this two weeks ago.

**Comment by ocefpaf** [comment] 2017-09-14 22:28
> @ocefpaf Any chance you could re-run this notebook and post how far back you need to filter the date by in order to get any of the SCRIPPS HFR records back?  

31 days

See https://gist.github.com/ocefpaf/b45877a314468f6c1e66dcf31eee610d

**Comment by benjwadams** [comment] 2017-09-26 20:21
I looked into this today and it looks like the logic used to determine whether a record is new is being falsely triggered for already existing datasets in the pycsw database.  This leads to a duplicate key trying to be inserted into the records table, which causes a failure.  I'm looking more into why this is occurring.

**Comment by mwengren** [comment] 2017-10-05 16:11
I had hoped to rerun the [notebook in question](https://github.com/ioos/notebooks_demos/blob/master/notebooks/2016-10-12-fetching_data.ipynb) this morning to check on the currency of those SCRIPPS records in the pycsw db, to get an update on @ocefpaf's most recent [test run](https://gist.github.com/ocefpaf/b45877a314468f6c1e66dcf31eee610d), but alas my feeble development environment here isn't up to the challenge.  At the moment, I can't run a conda env update command to pull in the ioos_tools package from Conda Forge.    So the notebook errors out at cell #5 for me at the ioos_tools import.  

But, my IT issues aside, let's keep on the pycsw sync issue and see if we can come up with a fix soon.  The [HF Radar](https://data.ioos.us/dataset/near-real-time-surface-ocean-velocity-u-s-west-coast1-km-resolution2) dataset seems to be updating at the IOOS Catalog level, most recent harvest date of 10/3, so it's clearly a problem at the pycsw db sync step.

**Comment by ocefpaf** [comment] 2017-10-05 16:19
> I had hoped to rerun the [notebook in question](https://github.com/ioos/notebooks_demos/blob/master/notebooks/2016-10-12-fetching_data.ipynb) this morning to check on the currency of those SCRIPPS records in the pycsw db, to get an update on @ocefpaf's most recent [test run](https://gist.github.com/ocefpaf/b45877a314468f6c1e66dcf31eee610d), 

Here is a new run,

http://nbviewer.ipython.org/urls/gist.githubusercontent.com/ocefpaf/b45877a314468f6c1e66dcf31eee610d/raw/1b73da1a8ff38759887d0ea99f281fc8ec20cb9d/debug_hfradar.ipynb

and things seems to be OK now. I was able to find data for the past 6 days.

> but alas my feeble development environment here isn't up to the challenge.  At the moment, I can't run a conda env update command to pull in the ioos_tools package from Conda Forge.    So the notebook errors out at cell #5 for me at the ioos_tools import. 

The `debug_hfradar.ipynb` does not use `ioos_tools`. I guess you are trying to run the original notebook. I'll take a look and fix it now that the data is back.

**Comment by benjwadams** [comment] 2017-10-05 16:53
@ocefpaf, I ran the notebook as well and reproduced your latest results.

**Comment by benjwadams** [comment] 2017-11-20 16:16
Closing as this now returns the HF Radar datasets.

**Closed by benjwadams** 2017-11-20 16:16 UTC
Labels: bug, in progress

**Comment by rsignell-usgs** [comment] 2017-11-20 19:08
I was excited to find hfradar data, but I searched for "hfradar" on catalog.ioos.us (https://data.ioos.us/dataset?q=hfradar) and then clicked on this dataset:

https://data.ioos.us/dataset/near-real-time-surface-ocean-velocity-u-s-eastand-gulf-coast-6-km-resolution

but when I try to access the the services links, they fail.  For example, the NCSS link: http://sdf.ndbc.noaa.gov/thredds/ncss/grid/hfradar_usegc_6km/dataset.html

**Comment by mwengren** [comment] 2017-11-20 19:44
@rsignell-usgs Thanks for the reminder.  I had noticed this last week, but then must have forgotten to make a new issue for it.  

NDBC moved their THREDDS server sometime recently, see  http://sdf.ndbc.noaa.gov/

This is why we need to pass the WAF generation process downstream to the data provider (whenever possible), since we had no idea or notice of the change.

The current WAF process I created last year is still looking for the old URL, and therefore not updating:  https://data.ioos.us/mwengren/hf_radar_dac_ndbc/.  Looks like they must have changed on the 15th.

**Comment by mwengren** [comment] 2017-11-21 21:28
@rsignell-usgs The NDBC TDS Server URL has been updated in our WAF cron job.  Those service links should now go to NDBC's new server:  http://dods.ndbc.noaa.gov/thredds/hfradar.html.

We'll be talking with them about handling the WAF generation themselves in the near future.

**Comment by rsignell-usgs** [comment] 2017-11-21 21:49
@mwengren Excellent.  Spiraling upwards!
